"""initial setup

Revision ID: 9bf1d59b7ed5
Revises:
Create Date: 2026-01-04 21:28:55.762447

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9bf1d59b7ed5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
